### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by SlvrEagle23**
Enjoy!

### CODE REVIEW

**Comment by dennybrandes** [comment]
If you need help with German translation, i can do this.

**Comment by jonikane** [comment]
Hello,

I am available to translate into Portuguese from Portugal.

**Comment by dennybrandes** [comment]
I started with translation for german today. Should be finished in few days. I also merged current master into this branch.

**Comment by duohost** [comment]
I have translated to Serbian. How to add it ?

**Pull request closed without merging**
