### PR TITLE
Implement #368 -- Add administrator-set storage quotas to individual stations.

### PR DESCRIPTION
**Pull request by SlvrEagle23**

### CODE REVIEW

**Comment by williambatson** [comment]
I just updated to check out the new quote system - I have 4 stations-  all 4 reporting 16gb used of the 10gb allocated.... including one station with nothing/no data.   What did I do wrong?
https://gyazo.com/2ba180807227954bc960fc6cb58f6aa1

**Comment by SlvrEagle23** [comment]
@williambatson Give it until the first 5-minute sync runs, or just manually run the 5-minute sync from the console administration. The default "used" size is the disk space used on the partition otherwise.

**Comment by williambatson** [comment]
hmmm -  mins says hasnt run in 24 mins, i clciked run task and got:
500
The given value "" does not represent a valid number.
BigNumber.php : 67

Now for sure I think I broke it!

**Comment by SlvrEagle23** [comment]
@williambatson Found and fixed an error relating to the new code; update and let me know if the sync task runs properly.

**Comment by williambatson** [comment]
Mostly right now -  ran the update, the stations with files already on them report correctly on the 5min update and now show properly on the music files page.
the only one with trouble is the one with 0 songs/data.. shows:
total_size
"0 (0.0 B)"
total_files
0
unchanged
0
updated
0
created
0
deleted
0
I have it set to 10gb -  files page still shows 16gb of 10gb used and will not allow uploads at all - uploads denied. - Again - the others with files already loaded seem fine now.

**Comment by SlvrEagle23** [comment]
@williambatson That one was caused by a bit of PHP fun (the string '0' is `empty` to PHP).

I've updated the code to not use the partition filled size if no file size is available.

Thanks for working with me on resolving this!

**Pull request merged**
