### PR TITLE
Restore missing annotateNextSong fixes from cpeter1207

### PR DESCRIPTION
**Pull request by Vaalyn**
**Fixes issue:**
#4239

**Proposed changes:**
This PR intends to restore the fixes that @cpeter1207 has contributed in August / September 2020 and that seem to have got partly lost in the refactoring of the AutoDJ [here](https://github.com/AzuraCast/AzuraCast/commit/55444a7baa449fb58f9cb36a91be448f8392fe1e#diff-d3f1af29a1881ab8736d8a8aa1ea201131f18699cad02fcae16e203fc6112f6fL67-L81).

### CODE REVIEW

**Comment by cpeter1207** [comment]
This nicely addresses the concern I had. I'll look forward to testing this when it's merged.

From: Vaalyn ***@***.***>
Sent: Friday, July 2, 2021 3:49 PM
To: AzuraCast/AzuraCast ***@***.***>
Cc: cpeter1207 ***@***.***>; Mention ***@***.***>
Subject: [AzuraCast/AzuraCast] Restore missing annotateNextSong fixes from cpeter1207 (#4373)


Fixes issue:
#4239<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzuraCast%2FAzuraCast%2Fissues%2F4239&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493746294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PHOnMq4Brn%2FMDjdPvwD09e3HEa%2Fh9SA3TvSATPCkca8%3D&reserved=0>

Proposed changes:
This PR intends to restore the fixes that @cpeter1207<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpeter1207&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493746294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DtfCGuPoEgCPQEQX1Ff7KAy1OdsV9%2FG%2FoffBKRlu%2FxI%3D&reserved=0> has contributed in August / September 2020 and that seem to have got partly lost in the refactoring of the AutoDJ here<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzuraCast%2FAzuraCast%2Fcommit%2F55444a7baa449fb58f9cb36a91be448f8392fe1e%23diff-d3f1af29a1881ab8736d8a8aa1ea201131f18699cad02fcae16e203fc6112f6fL67-L81&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493756294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=K3rh34gR3ox4PhOCXggmV1Q0H1rY%2BYueZiBy8fJgnPE%3D&reserved=0>.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/AzuraCast/AzuraCast/pull/4373<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzuraCast%2FAzuraCast%2Fpull%2F4373&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493766287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ti0X92AEx7g2Qek6odJ4eqpmWGnpsDQxTYXMoTmcWvU%3D&reserved=0>

Commit Summary

  *   Restore missing annotateNextSong fixes from cpeter1207

File Changes

  *   M src/Radio/AutoDJ.php<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzuraCast%2FAzuraCast%2Fpull%2F4373%2Ffiles%23diff-d3f1af29a1881ab8736d8a8aa1ea201131f18699cad02fcae16e203fc6112f6f&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493766287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ay3RxmN%2Fo%2B87BipUMPk5hJRTPapIxjs%2BsepLKmDZNEQ%3D&reserved=0> (12)

Patch Links:

  *   https://github.com/AzuraCast/AzuraCast/pull/4373.patch<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzuraCast%2FAzuraCast%2Fpull%2F4373.patch&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493776285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zl5%2F9Mf8cDyjzpFeZfKYYYjbpP3p3QmG2xro73IARqI%3D&reserved=0>
  *   https://github.com/AzuraCast/AzuraCast/pull/4373.diff<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzuraCast%2FAzuraCast%2Fpull%2F4373.diff&data=04%7C01%7C%7Ce0232b3a1c784bd2e3eb08d93d9ad6bf%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637608557493776285%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AotEhm20pzoBs0a%2FBmpoNxL8np8SpLBeDuGZg%2BKcwZ0%3D&reserved=0>

-

**Comment by Vaalyn** [comment]
@cpeter1207 do you have an installation of AzuraCast that you can use for testing this before we merge it?
I'd like to get your feedback on how this change works for you and if you can still notice anything unusual with it in place before we merge it so that we can make sure that nothing else is missing or going wrong there.

Since this is a single file change it is easy to manually mount the changed php file into the web container to test it.

You would basically need to download [this file](https://raw.githubusercontent.com/AzuraCast/AzuraCast/a1e5f590fb81621ee45f8580b66415468b5403ed/src/Radio/AutoDJ.php) into `/var/azuracast` and mount it into the `web` container with a `docker-compose.override.yml` like this:

```yml
version: '2.2'

services:
    web:
        volumes:
            - ./AutoDJ.php:/var/azuracast/www/src/Radio/AutoDJ.php:ro
```

and then restart AzuraCast via:

```bash
docker-compose down
docker-compose up -d
```

**Comment by cpeter1207** [comment]
Yes I have that set up now. I'll listen throughout the weekend and let you know how it goes.

**Comment by SlvrEagle23** [comment]
Looks good to me. I'd recommend testing it out to see if it improves things with AutoDJ scheduling. It's definitely possible that, in the big AutoDJ refactor, some of the logic got lost in the process, though I certainly did try to preserve it throughout that process.

**Comment by cpeter1207** [comment]
I've had this running since Saturday afternoon without issues. So far I like the results I'm hearing.

**Comment by SlvrEagle23** [comment]
@Vaalyn If this is running fine, this is a minor enough change to merge in without any complaints on my end. Feel free to untag it as WIP whenever you want.

**Review by SlvrEagle23 — APPROVED** [review]

**Pull request merged**
