### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by SlvrEagle23**
Enjoy!

### CODE REVIEW

**Comment by preterive** [comment]
How to edit Some Language Files?
The german Translation is already not very good.

**Comment by SlvrEagle23** [comment]
> How to edit Some Language Files?
> The german Translation is already not very good.

@preterive Translations are managed via CrowdIn at https://translate.azuracast.com/

**Comment by preterive** [comment]
Thanks! I will translate it today if I have time.

**Comment by djgaby7** [comment]
you can also add Romanian, I will try to translate

**Comment by susl16c** [comment]
[rus.zip](https://github.com/AzuraCast/AzuraCast/files/3410008/rus.zip)

**Comment by ogrenci01** [comment]
**Hello My Friend @SlvrEagle23 **

I have some good news for you. I finished the translation. AzuraCast is now in Turkish! I tested it. There is not problem. I want to share the default.pot file with you and use it for crowdin. Could you please tell me how to do this?

**Some screenshot for check:**

https://prnt.sc/orlv55

https://prnt.sc/orlv8c

**Comment by ogrenci01** [comment]
**Hello My Friend @SlvrEagle23 ;**

I have some good news for you. I finished the translation. AzuraCast is now in Turkish! I tested it. There is not problem. I want to share the default.pot file with you and use it for crowdin. Could you please tell me how to do this?

**Some screenshot for check:**

https://prnt.sc/orlv55

https://prnt.sc/orlv8c

**Pull request closed without merging**
