### PR TITLE
Fix 5002 Internal IP location

### PR DESCRIPTION
**Pull request by YosefAdPro**
**Fixes issue:**

#5002 
**Proposed changes:**

### CODE REVIEW

**Comment by SlvrEagle23** [comment]
I'm not sure why this actually fixes it. The proxy settings are defined higher up and should be pre-empting any of those settings...there should be no reason that redefining it farther down fixes it. 🤔

**Comment by YosefAdPro** [comment]
This may be because it is outside the parameter  `server {}`?

**Comment by YosefAdPro** [comment]
This may be because it is outside the parameter `server {}`?

Because when I put these two lines  into `location ~ ^/radio/` I got the  Public IP

**Comment by Vaalyn** [comment]
@SlvrEagle23 I think I know why it fixes the issue when it's set in the block like in this PR:

> The proxy_set_header directives are inherited from the previous level if and only if there are no proxy_set_header directives defined on the current level.

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

We have a `proxy_set_header Host localhost:$1;` in that block already so the previously defined one is not inherited.

**Comment by SlvrEagle23** [comment]
> @SlvrEagle23 I think I know why it fixes the issue when it's set in the block like in this PR:
> 
> > The proxy_set_header directives are inherited from the previous level if and only if there are no proxy_set_header directives defined on the current level.
> 
> http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header
> 
> We have a `proxy_set_header Host localhost:$1;` in that block already so the previously defined one is not inherited.

Well THAT'S frustrating, because we only need that `set-header` in that one block...

**Pull request merged**
