### PR TITLE
#3552 Fixes Sound Exchange Media Query

### LINKED ISSUE #3552: SoundExchange $all_media query fails (possibly outdated query)
**Using Docker installation method**
Yes

**AzuraCast version**
Rolling Release #aea5790

**Host Operating System**
MacOS High Sierra

**Describe the bug**
The $all_media DQL references sm.station_id on StationMedia.

**To Reproduce**
1. Go to `Reports -> SoundExchange Report`
2. Select a date range.
3. Click `Generate Report`
4. See error: 
```
[Semantical Error] line 0, col 63 near 'station_id =': Error: Class App\Entity\StationMedia has no field or association named station_id
```

**Expected behavior**
The report should be generated and download started.

**Relevant Logs**
```
Doctrine\ORM\Query\QueryException thrown with message "[Semantical Error] line 0, col 63 near 'station_id =': Error: Class App\Entity\StationMedia has no field or association named station_id"

Stacktrace:
#63 Doctrine\ORM\Query\QueryException in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:65
#62 Doctrine\ORM\Query\QueryException in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
#61 Doctrine\ORM\Query\QueryException:dqlError in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:506
#60 Doctrine\ORM\Query\Parser:semanticalError in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:779
#59 Doctrine\ORM\Query\Parser:processDeferredPathExpressions in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:284
#58 Doctrine\ORM\Query\Parser:getAST in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php:372
#57 Doctrine\ORM\Query\Parser:parse in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:287
#56 Doctrine\ORM\Query:_parse in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php:299
#55 Doctrine\ORM\Query:_doExecute in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1088
#54 Doctrine\ORM\AbstractQuery:executeIgnoreQueryCache in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:1042
#53 Doctrine\ORM\AbstractQuery:execute in /var/azuracast/www/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php:823
#52 Doctrine\ORM\AbstractQuery:getArrayResult in /var/azuracast/www/src/Controller/Stations/Reports/SoundExchangeController.php:68
#51 App\Controller\Stations\Reports\SoundExchangeController:__invoke in /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php:75
#50 call_user_func_array in /var/azuracast/www/vendor/php-di/invoker/src/Invoker.php:75
#49 Invoker\Invoker:call in /var/azuracast/www/vendor/php-di/slim-bridge/src/ControllerInvoker.php:47
#48 DI\Bridge\Slim\ControllerInvoker:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php:384
#47 Slim\Routing\Route:handle in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:81
#46 Slim\MiddlewareDispatcher:handle in /var/azuracast/www/src/Middleware/Permissions.php:52
#45 App\Middleware\Permissions:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:313
#44 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:294$163:handle in /var/azuracast/www/src/Middleware/Module/Stations.php:60
#43 App\Middleware\Module\Stations:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#42 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/Permissions.php:52
#41 App\Middleware\Permissions:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:313
#40 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:294$163:handle in /var/azuracast/www/src/Middleware/RequireStation.php:24
#39 App\Middleware\RequireStation:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#38 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/GetStation.php:55
#37 App\Middleware\GetStation:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#36 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/EnableView.php:35
#35 App\Middleware\EnableView:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#34 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/RequireLogin.php:25
#33 App\Middleware\RequireLogin:__invoke in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#32 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:81
#31 Slim\MiddlewareDispatcher:handle in /var/azuracast/www/vendor/slim/slim/Slim/Routing/Route.php:341
#30 Slim\Routing\Route:run in /var/azuracast/www/vendor/slim/slim/Slim/Routing/RouteRunner.php:84
#29 Slim\Routing\RouteRunner:handle in /var/azuracast/www/src/Middleware/WrapExceptionsWithRequestData.php:24
#28 App\Middleware\WrapExceptionsWithRequestData:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#27 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/EnforceSecurity.php:52
#26 App\Middleware\EnforceSecurity:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#25 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/InjectAcl.php:28
#24 App\Middleware\InjectAcl:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#23 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/GetCurrentUser.php:58
#22 App\Middleware\GetCurrentUser:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#21 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/InjectRouter.php:35
#20 App\Middleware\InjectRouter:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#19 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/InjectRateLimit.php:32
#18 App\Middleware\InjectRateLimit:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#17 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/src/Middleware/ReopenEntityManagerMiddleware.php:31
#16 App\Middleware\ReopenEntityManagerMiddleware:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#15 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/vendor/slim/slim/Slim/Middleware/BodyParsingMiddleware.php:68
#14 Slim\Middleware\BodyParsingMiddleware:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:147
#13 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$161:handle in /var/azuracast/www/vendor/slim/slim/Slim/Middleware/RoutingMiddleware.php:59
#12 Slim\Middleware\RoutingMiddleware:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:147
#11 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$161:handle in /var/azuracast/www/src/Middleware/RemoveSlashes.php:36
#10 App\Middleware\RemoveSlashes:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:147
#9 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$161:handle in /var/azuracast/www/src/Middleware/ApplyXForwardedProto.php:27
#8 App\Middleware\ApplyXForwardedProto:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:147
#7 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$161:handle in /var/azuracast/www/src/Middleware/InjectSession.php:51
#6 App\Middleware\InjectSession:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:209
#5 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:167$162:handle in /var/azuracast/www/vendor/slim/slim/Slim/Middleware/ErrorMiddleware.php:107
#4 Slim\Middleware\ErrorMiddleware:process in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:147
#3 class@anonymous�/var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:128$161:handle in /var/azuracast/www/vendor/slim/slim/Slim/MiddlewareDispatcher.php:81
#2 Slim\MiddlewareDispatcher:handle in /var/azuracast/www/vendor/slim/slim/Slim/App.php:215
#1 Slim\App:handle in /var/azuracast/www/vendor/slim/slim/Slim/App.php:199
#0 Slim\App:run in /var/azuracast/www/web/index.php:11

```

**Screenshots**

**Device(s):**
 - Device:  
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

It appears that at some point the data model was changed and this report's queries weren't updated. It probably needs to use something similar to what the `ListAction` controller uses to get all files.

### PR DESCRIPTION
**Pull request by bbene**
fixes #3552 

This feature is in a completely broken state. This PR fixes the `all_media` query as well as fixes an issue where the album titles weren't being properly populated.

### CODE REVIEW

**Comment by SlvrEagle23** [comment]
@bbene I'm trying to figure out where our CLA agreement bot has gone off to, since we require signing off on our contributor license agreement before merging any changes in on the main AzuraCast project.

Also, while I understand the purpose of optimizing the first query, I'm not sure switching to the QueryBuilder syntax affords any benefit in this case, as the raw DQL query can also handle partial entity loading just fine. Is there a particular reason for that change?

**Comment by bbene** [comment]
I took care of signing that before the bot could tell me I needed to. Did that mess with it somehow?

I'm more used to using query builders, but if the project's preference is DQL I can go ahead and switch it out.

**Comment by SlvrEagle23** [comment]
@bbene We only generally use the query builder when there's a logic fork that would change the query based on something in the code. In this case, the query never changes, so there's no reason not to just use raw DQL.

**Comment by bbene** [comment]
That makes perfect sense. I'll get it updated sometime today.

**Pull request merged**
